# Generated by Django 5.1.1 on 2024-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='progress',
            field=models.CharField(max_length=900),
        ),
    ]
