# Generated by Django 5.1.1 on 2024-09-18 20:04
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=800)),
                ('spent', models.IntegerField(max_length=2)),
            ],
        ),
    ]
