# Generated by Django 5.1.1 on 2024-09-12 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="spent",
        ),
        migrations.AddField(
            model_name="post",
            name="hours",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="minutes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
    ]
