# Generated by Django 5.1.1 on 2024-09-13 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_spent_post_hours_post_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
