# Generated by Django 5.1.1 on 2024-09-13 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
