# Generated by Django 5.1.1 on 2024-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='minutes',
            field=models.IntegerField(),
        ),
    ]
