# Generated by Django 5.1.1 on 2024-09-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(),
        ),
    ]
