# Generated by Django 5.1.1 on 2024-09-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
